# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e1d17bf12248515013ee5903268ef81f38b070d417f1abfdaa5d941281ae268134735d58fd3017db7ebab91118c4d0e0372070820d1df3d7ddecf60c9c5b45

test:
  secret_key_base: aa4310f307f9c6639e83963cadbc82ce635cfb46b9b0f761e8e5589c2493fb166eef2927492aeb1ee3c969e125ac5a6aa803f6f72eddb1e1590da34aa8c14766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
